### ISSUE TITLE
覃字为姓时读qin

### ISSUE THREAD

**Issue by szoliver** [toolgood/ToolGood.Words.Pinyin#2]
覃字为姓时读qin

**Comment by toolgood** [comment]
谢谢，还有几个多音姓字
召=shao4
占=zhan1
称=cheng1
繁=po2
皋=gao1
荤=hun2
冒=mao4
么=yao1
秘=bei4
辟=bi4
频=pin2
朴=piao2
其=qi2
系=xi4
校=xiao4
鉏=chu2
